<?php
header('Access-Control-Allow-Origin: *');
echo '[{
	"borderColor": "#b42c27",
	"fillColor": "#d9534f",
	"isClicked": false,
	"isSpecial": false,
	"point": 25,
	"position": 1,
	"offsetTime": 569,
	"id": 0,
    "offsetTop": 0,
	"offsetLeft": 23
}, {
	"borderColor": "#0000cc",
	"fillColor": "#0000ff",
	"isClicked": false,
	"isSpecial": false,
	"point": 25,
	"position": 2,
	"offsetTime": 897,
	"id": 1,
    "offsetTop": 0,
	"offsetLeft": 114
}, {
	"borderColor": "#ffe605",
	"fillColor": "#ffeb3b",
	"isClicked": false,
	"isSpecial": false,
	"point": 25,
	"position": 3,
	"offsetTime": 1216,
	"id": 2,
    "offsetTop": 0,
	"offsetLeft": 205
}, {
	"borderColor": "#0000cc",
	"fillColor": "#0000ff",
	"isClicked": false,
	"isSpecial": false,
	"point": 25,
	"position": 2,
	"offsetTime": 1536,
	"id": 3,
    "offsetTop": 0,
	"offsetLeft": 114
}, {
	"borderColor": "#b42c27",
	"fillColor": "#d9534f",
	"isClicked": false,
	"isSpecial": false,
	"point": 25,
	"position": 1,
	"offsetTime": 1872,
	"id": 4,
    "offsetTop": 0,
	"offsetLeft": 23
}, {
	"borderColor": "#b42c27",
	"fillColor": "#d9534f",
	"isClicked": false,
	"isSpecial": false,
	"point": 25,
	"position": 1,
	"offsetTime": 2215,
	"id": 5,
    "offsetTop": 0,
	"offsetLeft": 23
}, {
	"borderColor": "#b42c27",
	"fillColor": "#d9534f",
	"isClicked": false,
	"isSpecial": false,
	"point": 25,
	"position": 1,
	"offsetTime": 2560,
	"id": 6,
    "offsetTop": 0,
	"offsetLeft": 23
}]';
?>